import React from "react";
import BrandAd from "./BrandAds";

const SampleCopy = () => {
  return (
    <div className="overflow-y-auto">
      <h1 className="font-semibold text-2xl mb-5">
        The New York Pop-Up Revolution: A Culinary Adventure Awaits
      </h1>
      <p className="text-lg mb-5">
        New York City, a place where dreams are made of, and apparently,
        delicious pop-up restaurants are too. These fleeting culinary
        experiences have become a major foodie phenomenon, offering a chance to
        taste the latest trends and innovations from talented chefs before they
        disappear like a culinary mirage.
      </p>
      <p className="text-lg mb-5">
        From plant-based Peruvian cuisine to deconstructed takes on classic
        French dishes, pop-up restaurants cater to every adventurous palate. But
        what if you crave something a little unexpected with your exploration? A
        City Alive with Culinary Creativity The beauty of pop-up restaurants
        lies in their constant evolution. One week you might be savoring vegan
        ramen infused with unexpected citrus notes, the next you could be
        transported to a taste of Tuscany with a pop-up serving fresh pasta
        dishes made right before your eyes.
      </p>
      <p className="text-lg mb-5">
        The key to truly savoring these experiences is to approach them with an
        open mind and a willingness to experiment. Don't be afraid to step
        outside your comfort zone and try something completely new. After all,
        that's what makes the pop-up scene so exciting! Spice Up Your Pop-Up
        Adventure (if you dare!) For the truly adventurous eaters, there's
        always the option to bring your own flavor bomb to the table.
      </p>
      <p className="text-lg mb-5">
        Hot sauce connoisseurs might consider packing a travel-sized bottle of
        their favorite condiment to add an extra layer of complexity to their
        pop-up
      </p>
      <div>
        <BrandAd />
      </div>

      <p className="text-lg mb-5">
        Beyond the Plate: The Pop-Up Community Pop-up restaurants are more than
        just a meal; they're a chance to connect with the city's vibrant
        culinary community. Chat with the chefs, who are often eager to share
        their passion and inspiration. Mingle with fellow diners and swap
        stories about your latest pop-up finds. So next time you hear about a
        new pop-up in town, don't hesitate! Grab your adventurous spirit and
        head out to explore. You might just discover your new favorite dish, or
        even a hidden gem of a chef on the rise. With a little open-mindedness
        and a dash of exploration, you can turn the New York pop-up scene into
        your own personal culinary adventure.
      </p>
    </div>
  );
};

export default SampleCopy;
