import Head from "next/head";
import Hero from "../components/Hero";
import { useState } from "react";
import Tools from "../components/Tools";
import Influencer from "../components/Influencers";
import Affiliate from "../components/Affliate";
import Footer from "../components/Footer";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

//Read up on Replicate from replicate.com

export default function Home() {
  const [prediction, setPrediction] = useState(null);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const response = await fetch("/api/predictions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: e.target.prompt.value,
      }),
    });
    let prediction = await response.json();
    if (response.status !== 201) {
      setError(prediction.detail);
      return;
    }
    setPrediction(prediction);

    while (
      prediction.status !== "succeeded" &&
      prediction.status !== "failed"
    ) {
      await sleep(1000);
      const response = await fetch("/api/predictions/" + prediction.id);
      prediction = await response.json();
      if (response.status !== 200) {
        setError(prediction.detail);
        return;
      }
      console.log({ prediction });
      setPrediction(prediction);
    }
  };

  return (
    <>
      <Head>
        <title>ForgedMart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* Header */}
        <div>
          <Hero />
        </div>
        <div className=" flex justify-center content-center">
          <Tools />
        </div>
        <div className=" flex justify-center content-center mt-3">
          <Influencer />
        </div>
        <div className="mt-3">
          <Affiliate />
        </div>
      </main>
    </>
  );
}
